In [5]:
import pandas as pd

df = pd.read_csv('..\\data\\raw\\data.csv')

print(df.shape)
print(df.columns)

df.head()

(51, 2)
Index(['text', 'category'], dtype='str')

                                                text      category
0  Pandas is a powerful library for data manipula...        python
1  Pandas is a powerful library for data manipula...        python
2                                                NaN        python
3                                        Short text.       general
4    Machine   learning   models   are   only   a...  data_science

In [7]:
print("Пропуски:\n", df.isna().sum())

Пропуски:
 text        3
category    0
dtype: int64

In [8]:
print(df["text"].duplicated().sum())

5

In [10]:
df = df.dropna(subset=["text"])
print(df.shape)

(48, 2)

In [11]:
df = df.drop_duplicates(subset=["text"])
print(df.shape)

(45, 2)

In [15]:
df["text"] = df["text"].str.strip().str.replace(r"\s+", " ", regex=True)
df.head(10)

                                                 text      category
0   Pandas is a powerful library for data manipula...        python
3                                         Short text.       general
4   Machine learning models are only as good as th...  data_science
5                                    Git is for code.        devops
6   Data cleaning is the most important step in an...  data_science
7   Scikit-learn provides simple and efficient too...        python
10                                         Too short.       general
11  Feature engineering is the process of using do...  data_science
12  Neural networks are inspired by the biological...  data_science
13  Jupyter Notebook is an open-source web applica...        python

In [16]:
df = df[df["text"].str.len() > 50]
df.head(10)

                                                 text      category
0   Pandas is a powerful library for data manipula...        python
4   Machine learning models are only as good as th...  data_science
6   Data cleaning is the most important step in an...  data_science
7   Scikit-learn provides simple and efficient too...        python
11  Feature engineering is the process of using do...  data_science
12  Neural networks are inspired by the biological...  data_science
13  Jupyter Notebook is an open-source web applica...        python
14  Overfitting occurs when a model learns the det...  data_science
15  Cross-validation is a statistical method used ...  data_science
17  This is a text with weird spacing and tabs \t\...       general